### ISSUE TITLE
Plugin don't insert {$miunanewsfooter} in footer (custom theme)

### ISSUE THREAD

**Issue by rockenren** [martec/Miuna-News-Client#1]
I'm using custom theme on my forum.
Installed Miuna Client, activated it.

For some reason, plugin don't insert {$miunanewsfooter} variable in my active theme "footer" template, so all JS logic not working at all.

There is no problems with default MyBB theme, {$miunanewsfooter} is in place where it should be.

**Comment by martec** [comment]
about template i can't made anything if your custom template not following standard structure.
