### ISSUE TITLE
[Suggestion] Add MyProfile Comments!

### ISSUE THREAD

**Issue by saeed2060** [martec/Miuna-News-Client#2]
Hey to all.
Thanks for great plugin.
This very useful for me.
I use my alert and this is amazing for this and for threads , but i use MyProfile Comments Plugin:
https://github.com/medbenji/MyProfile
If sync this plugin with MyProfile Comments Plugin for Show ajax notification for receive comment is very amazing and this is complete for me very good.
This is possible?
Thanks for Great Work.

**Comment by martec** [comment]
if MyProfile Comments not has myalert support, i can't made anything.
You need wait this https://github.com/medbenji/MyProfile/issues/3
